name: PR Check

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop
    paths:
      - '**/*.js'  # Só roda se arquivos .js forem modificados

jobs:
  eslint:
    runs-on: ubuntu-latest
    continue-on-error: true # ⚠️ Não falha o PR se o ESLint tiver erro
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: ESLint changed files
        uses: tj-actions/eslint-changed-files@v25.3.1
        with:
          config_path: "eslint.config.js"
          extra_args: "--max-warnings=2"      

  build:
    runs-on: ubuntu-latest
    needs: eslint
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=test" >> .env
          echo "DB_USERNAME=test" >> .env
          echo "DB_PASSWORD=test" >> .env
          echo "PORT=5000" >> .env

      - name: Run Docker Compose
        run: |
          docker compose up --build -d
          sleep 20 # Aguarda o banco de dados iniciar
          # Verifica se o container está rodando
          if ! docker compose ps | grep backend | grep "Up"; then
            echo "❌ Backend container is not running!"
            docker compose logs backend
            exit 1
          else
            echo "✅ Backend container is running!"
            docker compose logs backend            
          fi                      
          docker compose down -v
          
