name: PR Check

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    continue-on-error: true # ⚠️ Não falha o PR se o ESLint tiver erro
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

  build:
    runs-on: ubuntu-latest
    needs: eslint
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=test" >> .env
          echo "DB_USERNAME=test" >> .env
          echo "DB_PASSWORD=test" >> .env
          echo "PORT=5000" >> .env

      - name: Run Docker Compose
        run: |
          docker compose up --build -d
          sleep 30 # Aguarda o banco de dados iniciar
          docker compose logs backend
          docker compose down -v